DEBUG =True
USERNAME = 'root'
PASSWORD = '24091974Luis*'
SERVER = 'localhost'
DB= 'gerenciamento_de_contas'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
"""TRABALHAR COM MIGRACOES NO DB"""

SECRET_KEY = '24091974Luis*'

