"""empty message

Revision ID: 33a54d3f4d21
Revises: 7154654428f4
Create Date: 2025-10-20 10:10:17.605530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a54d3f4d21'
down_revision = '7154654428f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('resumo', sa.String(length=50), nullable=False),
    sa.Column('custo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operacao')
    # ### end Alembic commands ###
