"""empty message

Revision ID: 7c6a93971e80
Revises: 33a54d3f4d21
Create Date: 2025-10-20 13:38:10.015339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6a93971e80'
down_revision = '33a54d3f4d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operacao', sa.Column('conta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operacao', 'contas', ['conta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operacao', type_='foreignkey')
    op.drop_column('operacao', 'conta_id')
    # ### end Alembic commands ###
